### ISSUE TITLE
mount error not caught

### ISSUE THREAD

**Issue by jalberge** [getzlab/canine#139]
A canine rodisk can be attached with correct mount point without being usable (error not caught during mount?)

https://github.com/getzlab/canine/blob/8235701ac8f9aee48772e1bce483cc27f35bea92/canine/localization/base.py#L1321-L1324

This happened to me on a disk marked as attached and mounted by two instances, but one is non-readable:

Instance with successful mount:
```{bash}
root@jb-2-worker3105:/tmp# ls /mnt/rodisks/canine-scratch-wpa4buy-ypljbha-ewdz3z3pxih0g-0
mybam.bam  dupe_metrics.txt
```
Instance without successful mount for the same disk:
```{bash}
root@jb-2-worker3103:/tmp# ls /mnt/rodisks/canine-scratch-wpa4buy-ypljbha-ewdz3z3pxih0g-0
ls: reading directory '/mnt/rodisks/canine-scratch-wpa4buy-ypljbha-ewdz3z3pxih0g-0': Input/output error
```

Catching a 1 exit status from `ls $CANINE_RODISK_DIR` might be a good option after `mountpoint -q` per https://superuser.com/a/864375 (we don't know how subsequent tasks may react to missing files...)

**Comment by julianhess** [comment]
Ugh, I thought that `mountpoint` would have caught this. I agree, adding an `ls` as an extra guardrail would be good.

**Comment by julianhess** [comment]
Fixed in https://github.com/getzlab/canine/commit/ef81a71610e84846aa8d50c1b5878571ee0cce36
