### ISSUE TITLE
orchestrator should attempt to run `delocalize.py` for jobs failed from node failures

### ISSUE THREAD

**Issue by agraubert** [getzlab/canine#50]
After the main batch completes, the orchestrator should make a second attempt at salvaging output files from failed jobs. Jobs which have too many node failures stop getting queued, but may have produced some output files.

## Which jobs receive 2nd chance delocalization

I think we could do a couple things here, either:
1) We check the `sacct` dataframe and perform 2nd chance delocalization on all jobs with a `NODE FAIL` slurm state
2) We run `localizer.build_manifest()` to check which jobs have any output files before files are delocalized. Then we can run 2nd chance delocalization on any jobs which do not appear in the manifest before running `localizer.delocalize()`

## The big picture

I think this will probably end up looking like

```python
orchestrator.wait_for_jobs_to_finish()
for job in select_second_chance_jobs():
    backend.invoke('SLURM_ARRAY_TASK_ID={job} . setup.sh && delocalize.py')
outputs = localizer.delocalize()
```

**Comment by julianhess** [comment]
Starting to work on this in https://github.com/broadinstitute/canine/pull/52.
