### ISSUE TITLE
Dummy backend on linux permissions issues

### ISSUE THREAD

**Issue by agraubert** [getzlab/canine#57]
I've noticed that on linux, there are still lingering issues with the dummy backend, particularly during cleanup. Since the container runs as root, any files written into the bind mount from the container are owned by root and usually write protected. This causes issues when the host tries to clean up the staging directory after killing the cluster.

I think the easiest workaround would be a two part approach:
1) Change root's umask in the docker image to be more permissive
2) Invoke `chmod -R` in the controller right before cleanup

I like that this doesn't involve the use of sudo, which may not be available to a user

**Comment by julianhess** [comment]
What about adding the user to the group `docker`, and having all containers run under the user, rather than under root?

This is the default behavior for the DockerTransient backend, and it works well.

**Comment by agraubert** [comment]
I think we can assume they're already in the docker group if the dummy backend successfully launches, but wouldn't baking their uid into the image only work for non-docker jobs that run directly in a worker container that we control? If someone tries to run a script that uses docker we'll run into the same problem

**Comment by julianhess** [comment]
Oh right. Let's go with the `chmod -R`, and pass in the UID/GID of the user through an environment variable (`-e` flag): 

We do this in wolF here: https://github.com/getzlab/wolF/blob/5e7ee233e913024a705f306a2d660ac6affcbf69/wolf/task.py#L303
